import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Check, Eye, EyeOff, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { api } from '../lib/api';
import { AuthFrame } from './Login';

export default function CreateAccount(){
 const[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false),[agreed,setAgreed]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 const checks=useMemo(()=>[{label:'8+ characters',ok:password.length>=8},{label:'Upper & lowercase',ok:/[A-Z]/.test(password)&&/[a-z]/.test(password)},{label:'At least one number',ok:/\d/.test(password)}],[password]);
 async function submit(e){e.preventDefault();setError('');if(name.trim().length<2)return setError('Enter your full name.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setError('Enter a valid business email.');if(checks.some(x=>!x.ok))return setError('Create a stronger password using the requirements below.');if(password!==confirm)return setError('Passwords do not match.');if(!agreed)return setError('Confirm that the information provided is accurate.');try{setLoading(true);await api.post('/auth/register',{name:name.trim(),email:email.trim(),password});setDone(true)}catch(err){setError(err.response?.data?.message||'Unable to create your account request.')}finally{setLoading(false)}}
 if(done)return <AuthFrame mode="register"><div className="auth-success"><span><Check size={25}/></span><p className="eyebrow">REQUEST RECEIVED</p><h1>Account submitted</h1><p>Your account is securely created and awaiting administrator approval. You can sign in after an administrator activates it and assigns company access.</p><Link className="auth-submit" to="/login"><ArrowLeft size={16}/>Back to sign in</Link></div></AuthFrame>;
 return <AuthFrame mode="register"><div className="auth-card-head"><p className="eyebrow">JOIN THE WORKSPACE</p><h1>Create your account</h1><p>Request secure access to your company workspace.</p></div><form className="auth-form" onSubmit={submit}><label><span>Full name</span><div className="auth-input"><UserRound size={16}/><input autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></div></label><label><span>Business email</span><div className="auth-input"><Mail size={16}/><input autoComplete="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></div></label><div className="auth-two"><label><span>Password</span><div className="auth-input"><LockKeyhole size={16}/><input autoComplete="new-password" type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Create password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label><label><span>Confirm password</span><div className="auth-input"><LockKeyhole size={16}/><input autoComplete="new-password" type={show?'text':'password'} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/></div></label></div><div className="password-checks">{checks.map(check=><span className={check.ok?'ok':''} key={check.label}><Check size={11}/>{check.label}</span>)}</div><label className="auth-agree"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)}/><span>I confirm these details are accurate and understand that an administrator must approve my access.</span></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={loading}>{loading?'Submitting request…':<>Request account<ArrowRight size={16}/></>}</button></form><div className="auth-switch">Already approved? <Link to="/login">Sign in</Link></div></AuthFrame>;
}
