import { useEffect, useMemo, useState } from 'react';
import { BadgeIndianRupee, Building2, CalendarDays, Download, Mail, Pencil, Phone, Plus, Search, ShieldCheck, Trash2, UserCheck, UserRound, Users, X } from 'lucide-react';
import { api, getPermissions, getUser } from '../lib/api';

const emptyForm={company_id:'',employee_code:'',name:'',designation:'',joining_date:'',salary:0,phone:'',email:'',status:'Active'};
const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v||0));
const initials=n=>String(n||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const fmtDate=v=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'Not provided';
const tenure=v=>{if(!v)return'Not available';const months=Math.max(0,Math.floor((Date.now()-new Date(v))/2629800000));return months<12?`${months} month${months===1?'':'s'}`:`${Math.floor(months/12)}y ${months%12}m`;};

export default function Employees(){
 const[rows,setRows]=useState([]),[companies,setCompanies]=useState([]),[query,setQuery]=useState(''),[company,setCompany]=useState('all'),[status,setStatus]=useState('all'),[selected,setSelected]=useState(null),[open,setOpen]=useState(false),[editingId,setEditingId]=useState(null),[form,setForm]=useState(emptyForm),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const user=getUser(),permissions=new Set(getPermissions()),canManage=user?.role==='group_admin'||permissions.has('employees.manage');
 const load=async()=>{setLoading(true);const[a,b]=await Promise.all([api.get('/employees').catch(()=>({data:[]})),api.get('/company-options').catch(()=>({data:[]}))]);setRows(a.data||[]);setCompanies(b.data||[]);setLoading(false)};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(company==='all'||String(r.company_id)===company)&&(status==='all'||r.status===status)&&(!query||[r.name,r.employee_code,r.designation,r.company_name,r.email,r.phone].join(' ').toLowerCase().includes(query.toLowerCase()))),[rows,company,status,query]);
 const active=rows.filter(r=>r.status==='Active').length,totalPayroll=rows.filter(r=>r.status==='Active').reduce((s,r)=>s+Number(r.salary||0),0),represented=new Set(rows.map(r=>r.company_id)).size;
 const create=()=>{setEditingId(null);setForm(emptyForm);setError('');setOpen(true)};
 const detail=async row=>{try{setSelected({...row,...(await api.get(`/employees/${row.id}`)).data})}catch{setSelected(row)}};
 const edit=async row=>{try{const d=(await api.get(`/employees/${row.id}`)).data;setForm({...emptyForm,...d,company_id:d.company_id||''});setEditingId(row.id);setSelected(null);setError('');setOpen(true)}catch(e){window.alert(e.response?.data?.message||'Unable to load employee.')}};
 const save=async e=>{e.preventDefault();setSaving(true);setError('');try{editingId?await api.put(`/employees/${editingId}`,form):await api.post('/employees',form);setOpen(false);setEditingId(null);await load()}catch(e){setError(e.response?.data?.message||e.response?.data?.detail||'Unable to save employee.')}finally{setSaving(false)}};
 const remove=async row=>{if(!window.confirm(`Delete ${row.name}? Associated payroll records will also be removed.`))return;try{await api.delete(`/employees/${row.id}`);setSelected(null);await load()}catch(e){window.alert(e.response?.data?.message||'Unable to delete employee.')}};
 const exportCsv=()=>{const esc=v=>`"${String(v??'').replaceAll('"','""')}"`,data=[['Code','Name','Company','Designation','Joining date','Salary','Phone','Email','Status'],...filtered.map(r=>[r.employee_code,r.name,r.company_name,r.designation,r.joining_date,r.salary,r.phone,r.email,r.status])],url=URL.createObjectURL(new Blob([`\uFEFF${data.map(x=>x.map(esc).join(',')).join('\n')}`],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='employee-directory.csv';a.click();URL.revokeObjectURL(url)};
 return <div className="page employees-page">
  <header className="employees-hero"><div className="employees-hero-icon"><Users size={24}/></div><div><p className="eyebrow">PEOPLE OPERATIONS</p><h1>Employees</h1><p>Manage your workforce, compensation and employment records across the group.</p></div>{canManage?<button onClick={create}><Plus size={17}/> Add employee</button>:<span><ShieldCheck size={15}/> Read-only access</span>}</header>
  <section className="employee-stats"><EmpStat icon={Users} label="Total employees" value={rows.length} note="Workforce records" tone="purple"/><EmpStat icon={UserCheck} label="Active workforce" value={active} note={`${rows.length-active} inactive`} tone="green"/><EmpStat icon={Building2} label="Companies" value={represented} note="With employees" tone="blue"/><EmpStat icon={BadgeIndianRupee} label="Monthly payroll base" value={money(totalPayroll)} note="Active base salaries" tone="amber"/></section>
  <div className="employee-toolbar"><div className="employee-search"><Search size={16}/><input placeholder="Search name, code, role or contact" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={company} onChange={e=>setCompany(e.target.value)}><option value="all">All companies</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option>Active</option><option>Inactive</option></select><button onClick={exportCsv}><Download size={15}/> Export</button></div>
  <section className="employee-table-card">{loading?<div className="employee-loading"/>:<div className="table-scroll"><table className="employee-table"><thead><tr><th>Employee</th><th>Employee ID</th><th>Company</th><th>Designation</th><th>Joined</th><th>Monthly salary</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map((r,i)=><tr key={r.id} onClick={()=>detail(r)}><td><div className="employee-identity"><span className={`employee-avatar tone-${i%5}`}>{initials(r.name)}</span><div><strong>{r.name}</strong><small>{r.email||'No email'}</small></div></div></td><td><code>{r.employee_code||'—'}</code></td><td>{r.company_name}</td><td>{r.designation||'—'}</td><td>{fmtDate(r.joining_date)}</td><td className="employee-salary">{money(r.salary)}</td><td><span className={`employee-status ${String(r.status).toLowerCase()}`}><i/>{r.status}</span></td><td>{canManage&&<button className="employee-edit" onClick={e=>{e.stopPropagation();edit(r)}}><Pencil size={14}/></button>}</td></tr>)}</tbody></table></div>}{!loading&&!filtered.length&&<div className="employee-empty"><Users size={24}/><strong>No employees found</strong><span>Change the filters or add your first employee.</span></div>}</section>
  {selected&&<div className="employee-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="employee-drawer"><div className="employee-drawer-head"><span>Employee profile</span><button onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="employee-profile"><div className="employee-avatar large tone-0">{initials(selected.name)}</div><span className={`employee-status ${String(selected.status).toLowerCase()}`}><i/>{selected.status}</span><h2>{selected.name}</h2><p>{selected.designation||'No designation'}</p><span><Building2 size={13}/>{selected.company_name||companies.find(c=>Number(c.id)===Number(selected.company_id))?.name}</span></div><section className="employee-profile-section"><h3>Employment details</h3><Info icon={UserRound} label="Employee ID" value={selected.employee_code}/><Info icon={CalendarDays} label="Joining date" value={fmtDate(selected.joining_date)} note={`${tenure(selected.joining_date)} tenure`}/><Info icon={BadgeIndianRupee} label="Monthly salary" value={money(selected.salary)} /></section><section className="employee-profile-section"><h3>Contact information</h3><Info icon={Mail} label="Email address" value={selected.email} href={selected.email?`mailto:${selected.email}`:null}/><Info icon={Phone} label="Phone number" value={selected.phone} href={selected.phone?`tel:${selected.phone}`:null}/></section>{canManage&&<div className="employee-profile-actions"><button className="secondary-btn employee-delete" onClick={()=>remove(selected)}><Trash2 size={15}/> Delete</button><button className="primary-btn" onClick={()=>edit(selected)}><Pencil size={15}/> Edit employee</button></div>}</aside></div>}
  {open&&<div className="employee-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!saving&&setOpen(false)}><form className="employee-modal" onSubmit={save}><div className="employee-modal-head"><div><p className="eyebrow">EMPLOYEE RECORD</p><h2>{editingId?'Edit employee':'Add employee'}</h2><span>Maintain employment, compensation and contact details.</span></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div>{error&&<div className="employee-form-error">{error}</div>}<div className="employee-form-grid"><Field label="Company" required><select required value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">Select company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Employee code"><input value={form.employee_code} onChange={e=>setForm({...form,employee_code:e.target.value})} placeholder="MCS-001"/></Field><Field label="Full name" required><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Designation"><input value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})} placeholder="Software Engineer"/></Field><Field label="Joining date"><input type="date" value={form.joining_date} onChange={e=>setForm({...form,joining_date:e.target.value})}/></Field><Field label="Monthly salary"><input type="number" min="0" step="0.01" value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})}/></Field><Field label="Phone number"><input type="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email address"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Employment status" full><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></Field></div><div className="employee-form-note"><ShieldCheck size={15}/><span>Salary and contact details are visible only to users with Employee module access.</span></div><div className="employee-modal-footer"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':editingId?'Update employee':'Add employee'}</button></div></form></div>}
 </div>
}
function EmpStat({icon:Icon,label,value,note,tone}){return <div className="employee-stat"><div className={`employee-stat-icon ${tone}`}><Icon size={18}/></div><span><small>{label}</small><strong>{value}</strong><em>{note}</em></span></div>}
function Field({label,required,full,children}){return <label className={`employee-field ${full?'full':''}`}><span>{label}{required?' *':''}</span>{children}</label>}
function Info({icon:Icon,label,value,note,href}){const content=<><div><Icon size={15}/></div><span><small>{label}</small><strong>{value||'Not provided'}</strong>{note&&<em>{note}</em>}</span></>;return href?<a className="employee-info" href={href}>{content}</a>:<div className="employee-info">{content}</div>}
