import { useEffect,useState } from 'react';
import { Boxes,Building2,ChartNoAxesCombined,Check,Handshake,Landmark,ReceiptText,WalletCards,XCircle } from 'lucide-react';
import { api } from '../lib/api';

const money=(v,c='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:c||'INR'}).format(Number(v||0));

export default function PartnerOperations(){
 const [partners,setPartners]=useState([]),[selected,setSelected]=useState(null),[detail,setDetail]=useState({companies:[],assets:[],transactions:[],investments:[]}),[withdrawals,setWithdrawals]=useState([]),[error,setError]=useState('');
 const loadWithdrawals=()=>api.get('/partner-admin/withdrawals').then(r=>setWithdrawals(r.data||[]));
 useEffect(()=>{Promise.all([api.get('/partner-admin/overview'),api.get('/partner-admin/withdrawals')]).then(([overview,requests])=>{setPartners(overview.data?.partners||[]);setWithdrawals(requests.data||[]);if(overview.data?.partners?.[0])choose(overview.data.partners[0].id)}).catch(e=>setError(e.response?.data?.message||'Unable to load partner operations.'))},[]);
 const choose=async id=>{setSelected(String(id));setDetail((await api.get(`/partner-admin/${id}`)).data||{})};
 const decide=async(row,status)=>{const admin_notes=window.prompt(status==='rejected'?'Enter the reason for rejection':'Optional administrator note')||'';try{await api.patch(`/partner-admin/withdrawals/${row.id}`,{status,admin_notes});await loadWithdrawals();if(selected)await choose(selected)}catch(err){setError(err.response?.data?.message||'Unable to update withdrawal request.')}};
 const assetValue=detail.assets?.reduce((s,x)=>s+Number(x.purchase_cost),0)||0,investment=detail.investments?.reduce((s,x)=>s+Number(x.amount),0)||0,income=detail.transactions?.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0)||0,expense=detail.transactions?.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0)||0;
 const openRequests=withdrawals.filter(x=>['pending','approved'].includes(x.status));
 return <div className="page partner-ops"><header className="partner-ops-hero"><span><ChartNoAxesCombined size={24}/></span><div><p className="eyebrow">PARTNER OVERSIGHT</p><h1>Partner Operations</h1><p>Monitor capital, withdrawals, assets and company transaction activity.</p></div><select value={selected||''} onChange={e=>choose(e.target.value)}><option value="">Select partner</option>{partners.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></header>{error&&<div className="partner-error">{error}</div>}<section className="partner-kpis colorful"><Kpi tone="purple" icon={Handshake} label="Recorded investment" value={money(investment)}/><Kpi tone="orange" icon={Boxes} label="Asset value" value={money(assetValue)}/><Kpi tone="green" label="Recent income" value={money(income)}/><Kpi tone="red" label="Recent expense" value={money(expense)}/></section><WithdrawalQueue rows={openRequests} decide={decide}/><section className="partner-ops-company">{detail.companies?.map((c,i)=><article className={`tone-${i%4}`} key={c.id}><Building2 size={18}/><div><strong>{c.company_name}</strong><small>{c.relationship_type} · {Number(c.ownership_percent).toFixed(2)}%</small></div><b>{money(c.invested_total,c.currency)}</b></article>)}</section><div className="partner-ops-grid"><section className="partner-ledger"><header><strong><Boxes size={15}/> Company assets</strong></header><div className="partner-table-scroll"><table><thead><tr><th>Asset</th><th>Company</th><th>Category</th><th>Status</th><th>Value</th></tr></thead><tbody>{detail.assets?.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.asset_code}</small></td><td>{a.company_name}</td><td>{a.category}</td><td>{a.status}</td><td>{money(a.purchase_cost,a.currency)}</td></tr>)}</tbody></table></div></section><section className="partner-ledger"><header><strong><ReceiptText size={15}/> Recent transactions</strong></header><div className="partner-table-scroll"><table><thead><tr><th>Date</th><th>Company</th><th>Type</th><th>Description</th><th>Amount</th></tr></thead><tbody>{detail.transactions?.map(t=><tr key={t.id}><td>{t.date}</td><td>{t.company_name}</td><td>{t.type}</td><td>{t.description}</td><td className={t.type==='expense'?'negative':''}>{money(t.amount,t.currency)}</td></tr>)}</tbody></table></div></section></div></div>;
}

function WithdrawalQueue({rows,decide}){return <section className="partner-withdraw-queue"><header><div><span><Landmark size={18}/></span><div><strong>Withdrawal approval queue</strong><small>Approve the request, then mark it paid only after funds are released.</small></div></div><b>{rows.length} open</b></header>{rows.map(row=><article key={row.id}><div><strong>{row.partner_name}</strong><small>{row.company_name} · {String(row.created_at).slice(0,10)}</small></div><p>{row.reason}<small>{row.payment_method}</small></p><strong>{money(row.amount,row.currency)}</strong><span className={`withdraw-status ${row.status}`}>{row.status}</span><div className="withdraw-actions">{row.status==='pending'&&<><button className="approve" onClick={()=>decide(row,'approved')}><Check size={14}/>Approve</button><button onClick={()=>decide(row,'rejected')}><XCircle size={14}/>Reject</button></>}{row.status==='approved'&&<button className="paid" onClick={()=>decide(row,'paid')}><WalletCards size={14}/>Mark paid</button>}</div></article>)}{!rows.length&&<div className="partner-empty"><Check size={22}/><span>No withdrawal requests need attention.</span></div>}</section>}
function Kpi({icon:Icon=WalletCards,label,value,tone}){return <div className={`partner-kpi ${tone}`}><span><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong></div></div>}
