import { useEffect, useMemo, useState } from 'react';
import {
  BadgeIndianRupee, Building2, CalendarDays, Check, CheckCircle2, Clock3,
  Download, Eye, FileText, Pencil, Plus, Printer, Search, ShieldCheck,
  Trash2, UserRound, Users, WalletCards, X
} from 'lucide-react';
import { api, getPermissions, getUser } from '../lib/api';

const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Number(value || 0));
const currentMonth = new Date().toISOString().slice(0, 7);
const today = new Date().toISOString().slice(0, 10);
const monthLabel = value => value ? new Date(`${value}-02`).toLocaleDateString('en-IN', { month: 'long', year: 'numeric' }) : '—';
const emptyForm = { employee_id: '', month: currentMonth, gross_salary: '', deduction: 0, status: 'Pending', paid_date: '' };

export default function Payroll() {
  const [rows, setRows] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [query, setQuery] = useState('');
  const [period, setPeriod] = useState(currentMonth);
  const [company, setCompany] = useState('all');
  const [status, setStatus] = useState('all');
  const [selected, setSelected] = useState(null);
  const [formOpen, setFormOpen] = useState(false);
  const [runOpen, setRunOpen] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState(emptyForm);
  const [run, setRun] = useState({ month: currentMonth, employeeIds: [], deduction: 0 });
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const user = getUser();
  const permissions = new Set(getPermissions());
  const canManage = user?.role === 'group_admin' || permissions.has('payroll.manage');

  const load = async () => {
    setLoading(true);
    const [payrollResult, employeeResult] = await Promise.all([api.get('/payroll').catch(() => ({ data: [] })), api.get('/payroll-employee-options').catch(() => ({ data: [] }))]);
    setRows(payrollResult.data || []); setEmployees(employeeResult.data || []); setLoading(false);
  };
  useEffect(() => { load(); }, []);
  const companies = useMemo(() => [...new Set(rows.map(r => r.company_name).filter(Boolean))].sort(), [rows]);
  const filtered = useMemo(() => rows.filter(row => (period === 'all' || row.month === period) && (company === 'all' || row.company_name === company) && (status === 'all' || row.status === status) && (!query || JSON.stringify(row).toLowerCase().includes(query.toLowerCase()))), [rows, query, period, company, status]);
  const totals = useMemo(() => ({ gross: filtered.reduce((s,r) => s + Number(r.gross_salary || 0), 0), deductions: filtered.reduce((s,r) => s + Number(r.deduction || 0), 0), net: filtered.reduce((s,r) => s + Number(r.net_salary || 0), 0), paid: filtered.filter(r => r.status === 'Paid').reduce((s,r) => s + Number(r.net_salary || 0), 0) }), [filtered]);

  const openCreate = () => { setEditingId(null); setForm(emptyForm); setError(''); setFormOpen(true); };
  const selectEmployee = id => { const employee = employees.find(e => Number(e.id) === Number(id)); setForm(current => ({ ...current, employee_id: id, gross_salary: employee?.salary || current.gross_salary })); };
  const openEdit = async row => { try { const detail = (await api.get(`/payroll/${row.id}`)).data; setForm({ ...emptyForm, ...detail, paid_date: detail.paid_date || '' }); setEditingId(row.id); setSelected(null); setError(''); setFormOpen(true); } catch (err) { window.alert(err.response?.data?.message || 'Unable to load payroll record.'); } };
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { const payload = { ...form, paid_date: form.status === 'Paid' ? (form.paid_date || today) : '' }; if (editingId) await api.put(`/payroll/${editingId}`, payload); else await api.post('/payroll', payload); setFormOpen(false); setEditingId(null); await load(); } catch (err) { setError(err.response?.data?.message || err.response?.data?.detail || 'Unable to save payroll record.'); } finally { setSaving(false); } };
  const viewPayslip = async row => { try { const detail = (await api.get(`/payroll/${row.id}`)).data; setSelected({ ...row, ...detail }); } catch { setSelected(row); } };
  const transition = async (row, nextStatus) => { if (!window.confirm(`${nextStatus === 'Paid' ? 'Mark' : 'Move'} ${row.employee_name}'s ${monthLabel(row.month)} payroll as ${nextStatus}?`)) return; try { const detail = (await api.get(`/payroll/${row.id}`)).data; await api.put(`/payroll/${row.id}`, { ...detail, status: nextStatus, paid_date: nextStatus === 'Paid' ? today : '' }); await load(); } catch (err) { window.alert(err.response?.data?.message || 'Unable to update payroll status.'); } };
  const remove = async row => { if (!window.confirm(`Delete ${row.employee_name}'s ${monthLabel(row.month)} payroll record?`)) return; try { await api.delete(`/payroll/${row.id}`); setSelected(null); await load(); } catch (err) { window.alert(err.response?.data?.message || 'Unable to delete payroll record.'); } };

  const openMonthlyRun = () => { const existing = new Set(rows.filter(r => r.month === currentMonth).map(r => Number(r.employee_id))); setRun({ month: currentMonth, employeeIds: employees.filter(e => !existing.has(Number(e.id))).map(e => e.id), deduction: 0 }); setError(''); setRunOpen(true); };
  const processRun = async event => { event.preventDefault(); setSaving(true); setError(''); const chosen = employees.filter(e => run.employeeIds.map(Number).includes(Number(e.id))); const results = await Promise.allSettled(chosen.map(employee => api.post('/payroll', { employee_id: employee.id, month: run.month, gross_salary: employee.salary || 0, deduction: run.deduction || 0, status: 'Pending', paid_date: '' }))); const failed = results.filter(r => r.status === 'rejected'); setSaving(false); await load(); if (failed.length) setError(`${results.length - failed.length} records created; ${failed.length} could not be created (usually because payroll already exists).`); else { setRunOpen(false); setPeriod(run.month); } };
  const toggleRunEmployee = id => setRun(current => ({ ...current, employeeIds: current.employeeIds.map(Number).includes(Number(id)) ? current.employeeIds.filter(value => Number(value) !== Number(id)) : [...current.employeeIds, id] }));
  const exportCsv = () => { const escape = value => `"${String(value ?? '').replaceAll('"','""')}"`; const data = [['Month','Employee','Company','Gross','Deductions','Net','Status'],...filtered.map(r => [r.month,r.employee_name,r.company_name,r.gross_salary,r.deduction,r.net_salary,r.status])]; const url=URL.createObjectURL(new Blob([`\uFEFF${data.map(row=>row.map(escape).join(',')).join('\n')}`],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`payroll-${period}.csv`;link.click();URL.revokeObjectURL(url); };

  return <div className="page payroll-page">
    <header className="payroll-hero"><div className="payroll-hero-icon"><BadgeIndianRupee size={24}/></div><div><p className="eyebrow">PEOPLE & COMPENSATION</p><h1>Payroll</h1><p>Prepare, approve and track employee salary payments across the group.</p></div>{canManage ? <div className="payroll-hero-actions"><button onClick={openCreate}><Plus size={16}/> Single payroll</button><button className="primary" onClick={openMonthlyRun}><Users size={16}/> Run monthly payroll</button></div> : <span className="payroll-readonly"><ShieldCheck size={15}/> Read-only access</span>}</header>
    <section className="payroll-stats"><PayrollStat icon={WalletCards} label="Gross payroll" value={money(totals.gross)} note={monthLabel(period === 'all' ? currentMonth : period)} tone="navy"/><PayrollStat icon={FileText} label="Deductions" value={money(totals.deductions)} note="Total deductions" tone="amber"/><PayrollStat icon={BadgeIndianRupee} label="Net payable" value={money(totals.net)} note={`${filtered.length} salary records`} tone="blue"/><PayrollStat icon={CheckCircle2} label="Paid" value={money(totals.paid)} note={`${filtered.filter(r=>r.status==='Paid').length} completed`} tone="green"/></section>
    <div className="payroll-toolbar"><div className="payroll-search"><Search size={16}/><input placeholder="Search employee or company" value={query} onChange={e=>setQuery(e.target.value)}/></div><input type="month" value={period==='all'?'':period} onChange={e=>setPeriod(e.target.value||'all')}/><select value={company} onChange={e=>setCompany(e.target.value)}><option value="all">All companies</option>{companies.map(c=><option key={c}>{c}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{['Pending','Approved','Paid'].map(s=><option key={s}>{s}</option>)}</select><button className="payroll-export" onClick={exportCsv}><Download size={15}/> Export</button></div>
    <section className="payroll-table-card">{loading?<div className="payroll-loading"/>:<div className="table-scroll"><table className="payroll-table"><thead><tr><th>Employee</th><th>Pay period</th><th>Gross salary</th><th>Deductions</th><th>Net salary</th><th>Status</th><th>Workflow</th><th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><div className="payroll-person"><span>{String(row.employee_name||'?').slice(0,2).toUpperCase()}</span><div><strong>{row.employee_name}</strong><small>{row.company_name}</small></div></div></td><td>{monthLabel(row.month)}</td><td>{money(row.gross_salary)}</td><td>{money(row.deduction)}</td><td className="payroll-net">{money(row.net_salary)}</td><td><span className={`payroll-status ${row.status.toLowerCase()}`}><i/>{row.status}</span></td><td>{canManage&&row.status==='Pending'?<button className="payroll-workflow" onClick={()=>transition(row,'Approved')}><Check size={13}/> Approve</button>:canManage&&row.status==='Approved'?<button className="payroll-workflow pay" onClick={()=>transition(row,'Paid')}><BadgeIndianRupee size={13}/> Mark paid</button>:<span className="payroll-complete">{row.status==='Paid'?'Complete':'—'}</span>}</td><td><div className="payroll-row-actions"><button title="View payslip" onClick={()=>viewPayslip(row)}><Eye size={14}/></button>{canManage&&row.status!=='Paid'&&<button title="Edit" onClick={()=>openEdit(row)}><Pencil size={14}/></button>}</div></td></tr>)}</tbody></table></div>}{!loading&&!filtered.length&&<div className="payroll-empty"><FileText size={24}/><strong>No payroll records found</strong><span>Change the filters or create payroll for this period.</span></div>}</section>

    {selected&&<div className="payslip-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><aside className="payslip-drawer"><div className="payslip-top no-print"><span>Payslip preview</span><button onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="payslip-document"><header><div className="payslip-logo"><BadgeIndianRupee size={22}/></div><div><strong>{selected.company_name}</strong><span>Employee payslip</span></div><b>{monthLabel(selected.month)}</b></header><section className="payslip-employee"><div><span>EMPLOYEE</span><strong>{selected.employee_name}</strong><small>Employee ID: {selected.employee_id}</small></div><span className={`payroll-status ${String(selected.status).toLowerCase()}`}><i/>{selected.status}</span></section><section className="payslip-breakdown"><h3>Earnings and deductions</h3><div><span>Gross salary</span><strong>{money(selected.gross_salary)}</strong></div><div><span>Total deductions</span><strong className="deduct">− {money(selected.deduction)}</strong></div><div className="payslip-net"><span>Net salary</span><strong>{money(selected.net_salary)}</strong></div></section><section className="payslip-meta"><div><span>Pay period</span><strong>{monthLabel(selected.month)}</strong></div><div><span>Payment date</span><strong>{selected.paid_date||'Not paid'}</strong></div><div><span>Payment status</span><strong>{selected.status}</strong></div></section><footer>This is a system-generated payroll statement.</footer></div><div className="payslip-actions no-print"><button className="secondary-btn" onClick={()=>window.print()}><Printer size={15}/> Print payslip</button>{canManage&&<button className="secondary-btn payroll-delete" onClick={()=>remove(selected)}><Trash2 size={15}/> Delete record</button>}</div></aside></div>}

    {formOpen&&<PayrollForm title={editingId?'Edit payroll':'Create payroll'} form={form} setForm={setForm} employees={employees} onSelectEmployee={selectEmployee} onSubmit={save} onClose={()=>setFormOpen(false)} saving={saving} error={error}/>} 
    {runOpen&&<div className="payroll-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!saving&&setRunOpen(false)}><form className="payroll-modal run-modal" onSubmit={processRun}><ModalHead title="Run monthly payroll" subtitle="Create pending payroll records for multiple employees." onClose={()=>setRunOpen(false)}/>{error&&<div className="payroll-form-error">{error}</div>}<div className="run-settings"><label><span>Pay period</span><input required type="month" value={run.month} onChange={e=>setRun({...run,month:e.target.value})}/></label><label><span>Common deduction</span><input type="number" min="0" value={run.deduction} onChange={e=>setRun({...run,deduction:e.target.value})}/></label></div><div className="run-select-head"><span>Select employees</span><button type="button" onClick={()=>setRun({...run,employeeIds:run.employeeIds.length===employees.length?[]:employees.map(e=>e.id)})}>{run.employeeIds.length===employees.length?'Clear all':'Select all'}</button></div><div className="run-employee-list">{employees.map(employee=><label key={employee.id}><input type="checkbox" checked={run.employeeIds.map(Number).includes(Number(employee.id))} onChange={()=>toggleRunEmployee(employee.id)}/><span><strong>{employee.name}</strong><small>{employee.company_name}</small></span><b>{money(employee.salary)}</b></label>)}</div><div className="payroll-modal-footer"><span>{run.employeeIds.length} employees selected</span><div><button type="button" className="secondary-btn" onClick={()=>setRunOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving||!run.employeeIds.length}>{saving?'Processing…':'Create payroll run'}</button></div></div></form></div>}
  </div>;
}

function PayrollForm({title,form,setForm,employees,onSelectEmployee,onSubmit,onClose,saving,error}){const net=Math.max(0,Number(form.gross_salary||0)-Number(form.deduction||0));return <div className="payroll-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!saving&&onClose()}><form className="payroll-modal" onSubmit={onSubmit}><ModalHead title={title} subtitle="Set compensation, deductions and workflow status." onClose={onClose}/>{error&&<div className="payroll-form-error">{error}</div>}<div className="payroll-form-grid"><PayrollField label="Employee" required><select required value={form.employee_id} onChange={e=>onSelectEmployee(e.target.value)}><option value="">Select employee</option>{employees.map(e=><option value={e.id} key={e.id}>{e.name} — {e.company_name}</option>)}</select></PayrollField><PayrollField label="Pay period" required><input required type="month" value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/></PayrollField><PayrollField label="Gross salary" required><input required type="number" min="0" step="0.01" value={form.gross_salary} onChange={e=>setForm({...form,gross_salary:e.target.value})}/></PayrollField><PayrollField label="Deductions"><input type="number" min="0" max={form.gross_salary||undefined} step="0.01" value={form.deduction} onChange={e=>setForm({...form,deduction:e.target.value})}/></PayrollField><PayrollField label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value,paid_date:e.target.value==='Paid'?(form.paid_date||today):''})}>{['Pending','Approved','Paid'].map(s=><option key={s}>{s}</option>)}</select></PayrollField>{form.status==='Paid'&&<PayrollField label="Paid date" required><input required type="date" value={form.paid_date} onChange={e=>setForm({...form,paid_date:e.target.value})}/></PayrollField>}</div><div className="payroll-net-preview"><span>Calculated net salary</span><strong>{money(net)}</strong><small>Gross salary less deductions</small></div><div className="payroll-modal-footer"><span/><div><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':'Save payroll'}</button></div></div></form></div>}
function ModalHead({title,subtitle,onClose}){return <div className="payroll-modal-head"><div><p className="eyebrow">PAYROLL WORKFLOW</p><h2>{title}</h2><span>{subtitle}</span></div><button type="button" onClick={onClose}><X size={18}/></button></div>}
function PayrollField({label,required,children}){return <label className="payroll-field"><span>{label}{required?' *':''}</span>{children}</label>}
function PayrollStat({icon:Icon,label,value,note,tone}){return <div className="payroll-stat"><div className={`payroll-stat-icon ${tone}`}><Icon size={18}/></div><span><small>{label}</small><strong>{value}</strong><em>{note}</em></span></div>}
