import { useEffect,useMemo,useState } from 'react';
import { BellRing,Building2,CalendarDays,Check,Clock3,Download,Pencil,Plus,RefreshCw,Search,ShieldCheck,Trash2,X } from 'lucide-react';
import { api,getPermissions,getUser } from '../lib/api';
const today=new Date().toISOString().slice(0,10),empty={company_id:'',title:'',category:'',due_date:today,priority:'Medium',status:'pending',recurrence:'',notes:''};
const fmt=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';
const days=v=>Math.ceil((new Date(`${v}T23:59:59`)-Date.now())/86400000);
export default function Reminders(){
 const[rows,setRows]=useState([]),[companies,setCompanies]=useState([]),[query,setQuery]=useState(''),[company,setCompany]=useState('all'),[status,setStatus]=useState('pending'),[priority,setPriority]=useState('all'),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[editingId,setEditingId]=useState(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const user=getUser(),permissions=new Set(getPermissions()),canManage=user?.role==='group_admin'||permissions.has('reminders.manage');
 const load=async()=>{setLoading(true);const[a,b]=await Promise.all([api.get('/reminders').catch(()=>({data:[]})),api.get('/company-options').catch(()=>({data:[]}))]);setRows(a.data||[]);setCompanies(b.data||[]);setLoading(false)};useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>(company==='all'||String(r.company_id)===company)&&(status==='all'||r.status===status)&&(priority==='all'||r.priority===priority)&&(!query||[r.title,r.category,r.company_name].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>a.due_date.localeCompare(b.due_date)),[rows,company,status,priority,query]);
 const overdue=rows.filter(r=>r.status==='pending'&&r.due_date<today).length,week=rows.filter(r=>r.status==='pending'&&days(r.due_date)>=0&&days(r.due_date)<=7).length,completed=rows.filter(r=>r.status==='completed').length;
 const create=()=>{setEditingId(null);setForm(empty);setError('');setOpen(true)};
 const edit=async r=>{try{const d=(await api.get(`/reminders/${r.id}`)).data;setForm({...empty,...d,company_id:d.company_id||''});setEditingId(r.id);setError('');setOpen(true)}catch(e){window.alert(e.response?.data?.message||'Unable to load reminder.')}};
 const save=async e=>{e.preventDefault();setSaving(true);setError('');try{editingId?await api.put(`/reminders/${editingId}`,form):await api.post('/reminders',form);setOpen(false);await load()}catch(e){setError(e.response?.data?.message||'Unable to save reminder.')}finally{setSaving(false)}};
 const changeStatus=async(r,next)=>{try{const d=(await api.get(`/reminders/${r.id}`)).data;await api.put(`/reminders/${r.id}`,{...d,status:next});await load()}catch(e){window.alert(e.response?.data?.message||'Unable to update reminder.')}};
 const remove=async r=>{if(!window.confirm(`Delete reminder “${r.title}”?`))return;try{await api.delete(`/reminders/${r.id}`);await load()}catch(e){window.alert(e.response?.data?.message||'Unable to delete reminder.')}};
 const exportCsv=()=>{const esc=v=>`"${String(v??'').replaceAll('"','""')}"`,data=[['Due date','Title','Company','Category','Priority','Status'],...filtered.map(r=>[r.due_date,r.title,r.company_name,r.category,r.priority,r.status])],url=URL.createObjectURL(new Blob([`\uFEFF${data.map(r=>r.map(esc).join(',')).join('\n')}`],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='reminders.csv';a.click();URL.revokeObjectURL(url)};
 return <div className="page reminders-page"><header className="reminders-hero"><div className="reminders-hero-icon"><BellRing size={24}/></div><div><p className="eyebrow">OBLIGATIONS & DEADLINES</p><h1>Reminders</h1><p>Track renewals, rent, compliance dates and recurring group obligations.</p></div>{canManage?<button onClick={create}><Plus size={17}/>Add reminder</button>:<span><ShieldCheck size={15}/>Read-only access</span>}</header>
 <section className="reminder-stats"><RStat icon={BellRing} label="Pending" value={rows.filter(r=>r.status==='pending').length} note="Open obligations" tone="purple"/><RStat icon={Clock3} label="Overdue" value={overdue} note="Requires attention" tone="red"/><RStat icon={CalendarDays} label="Due this week" value={week} note="Next 7 days" tone="amber"/><RStat icon={Check} label="Completed" value={completed} note="Closed reminders" tone="green"/></section>
 <div className="reminder-toolbar"><div className="reminder-search"><Search size={16}/><input placeholder="Search reminders or categories" value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={company} onChange={e=>setCompany(e.target.value)}><option value="all">All companies</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option>{['High','Medium','Low'].map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button onClick={exportCsv}><Download size={15}/>Export</button></div>
 <section className="reminder-list">{loading?<div className="reminder-loading"/>:filtered.map(r=>{const d=days(r.due_date),late=r.status==='pending'&&d<0;return <article className={`reminder-row ${late?'overdue':''}`} key={r.id}><div className="reminder-date"><span>{new Date(`${r.due_date}T00:00:00`).toLocaleString('en',{month:'short'})}</span><strong>{new Date(`${r.due_date}T00:00:00`).getDate()}</strong></div><div className="reminder-main"><div><span className={`reminder-priority ${String(r.priority).toLowerCase()}`}>{r.priority}</span><span className="reminder-category">{r.category||'General'}</span></div><h2>{r.title}</h2><p><Building2 size={12}/>{r.company_name||'Group-level'}<i/> {late?`${Math.abs(d)} days overdue`:d===0?'Due today':`Due ${fmt(r.due_date)}`}</p></div><span className={`reminder-status ${r.status}`}>{r.status}</span>{canManage&&<div className="reminder-actions">{r.status==='pending'?<button title="Mark complete" onClick={()=>changeStatus(r,'completed')}><Check size={15}/></button>:r.status==='completed'&&<button title="Reopen" onClick={()=>changeStatus(r,'pending')}><RefreshCw size={14}/></button>}<button title="Edit" onClick={()=>edit(r)}><Pencil size={14}/></button><button title="Delete" onClick={()=>remove(r)}><Trash2 size={14}/></button></div>}</article>})}{!loading&&!filtered.length&&<div className="reminder-empty"><BellRing size={24}/><strong>No reminders found</strong><span>Change the filters or add a new obligation.</span></div>}</section>
 {open&&<div className="reminder-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!saving&&setOpen(false)}><form className="reminder-modal" onSubmit={save}><div className="reminder-modal-head"><div><p className="eyebrow">REMINDER WORKFLOW</p><h2>{editingId?'Edit reminder':'Add reminder'}</h2><span>Schedule a deadline, renewal or recurring obligation.</span></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div>{error&&<div className="reminder-form-error">{error}</div>}<div className="reminder-form-grid"><Field label="Reminder title" full><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Company"><select value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">Group / no specific company</option>{companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Category"><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Compliance, Rent, Domain…"/></Field><Field label="Due date"><input required type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Field><Field label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['High','Medium','Low'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Recurrence"><input value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})} placeholder="Monthly, yearly, none"/></Field><Field label="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="pending">Pending</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></Field><Field label="Notes" full><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className="reminder-modal-footer"><button type="button" className="secondary-btn" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':editingId?'Update reminder':'Add reminder'}</button></div></form></div>}</div>
}
function RStat({icon:Icon,label,value,note,tone}){return <div className="reminder-stat"><div className={`reminder-stat-icon ${tone}`}><Icon size={18}/></div><span><small>{label}</small><strong>{value}</strong><em>{note}</em></span></div>}
function Field({label,full,children}){return <label className={`reminder-field ${full?'full':''}`}><span>{label}</span>{children}</label>}
