import { useEffect, useMemo, useState } from 'react';
import { CalendarClock, CircleDollarSign, HandCoins, Landmark, Plus, UserRound, X } from 'lucide-react';
import { api } from '../../lib/api';

const today=()=>new Date().toISOString().slice(0,10);
const money=(value,currency='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:currency||'INR',maximumFractionDigits:2}).format(Number(value||0));
const empty={company_id:'',investor_name:'',phone:'',email:'',id_number:'',investment_amount:'',interest_rate:'',interest_type:'percentage',investment_date:today(),next_interest_date:today(),payment_method:'Bank transfer',reference_no:'',notes:''};

export default function Investors(){
  const [data,setData]=useState({companies:[],investors:[],summary:{}}),[modal,setModal]=useState(null),[payments,setPayments]=useState([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[filter,setFilter]=useState('active');
  const load=async()=>setData((await api.get('/investors/overview')).data||{});
  useEffect(()=>{load().catch(err=>setError(err.response?.data?.message||'Unable to load investors.'));},[]);
  const visible=useMemo(()=>data.investors.filter(row=>filter==='all'||(filter==='due'?row.status==='active'&&row.next_interest_date<=today():row.status===filter)),[data.investors,filter]);
  const openAdd=()=>setModal({...empty,type:'add',company_id:data.companies[0]?.id||''});
  const create=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.post('/investors',modal);setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to add investor.')}finally{setSaving(false)}};
  const openPay=row=>setModal({type:'pay',row,periods_count:1,amount:row.monthly_interest_amount,payment_date:today(),payment_method:row.payment_method||'Bank transfer',reference_no:'',notes:''});
  const pay=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.post(`/investors/${modal.row.id}/payments`,modal);setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to record interest payment.')}finally{setSaving(false)}};
  const history=async row=>{setPayments((await api.get(`/investors/${row.id}/payments`)).data||[]);setModal({type:'history',row});};
  const toggle=async row=>{await api.patch(`/investors/${row.id}/status`,{status:row.status==='active'?'closed':'active'});await load();};
  const s=data.summary||{};
  return <div className="investors-page">
    <section className="collection-admin-head"><div><p className="eyebrow">INVESTMENT LIABILITIES</p><h2>Investors & monthly interest</h2><p>Record investment received by each company and manage the monthly interest paid to investors.</p></div><button className="primary-btn" onClick={openAdd}><Plus size={15}/>Add investor</button></section>
    {error&&<div className="finance-error">{error}</div>}
    <section className="collection-admin-metrics"><Metric icon={UserRound} label="Active investors" value={s.active_investors||0}/><Metric icon={Landmark} label="Investment received" value={money(s.investment_received)}/><Metric icon={CalendarClock} label="Monthly interest payable" value={money(s.monthly_interest_payable)}/><Metric icon={HandCoins} label="Paid this month" value={money(s.paid_this_month)} note={`${s.due_now||0} currently due`}/></section>
    <section className="finance-list-card"><header className="investor-list-head"><div><strong>Investor accounts</strong><span>Investment principal and recurring monthly payout schedule</span></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active</option><option value="due">Due / overdue</option><option value="closed">Closed</option><option value="all">All</option></select></header><div className="finance-table-scroll"><table className="finance-table"><thead><tr><th>Investor</th><th>Company</th><th>Investment received</th><th>Monthly interest</th><th>Next payout</th><th>Interest paid</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(row=>{const due=row.status==='active'&&row.next_interest_date<=today();return <tr key={row.id}><td><strong>{row.investor_name}</strong><small>{row.phone||row.email||row.id_number||'No contact details'}</small></td><td>{row.company_name}</td><td className="finance-money">{money(row.investment_amount,row.currency)}</td><td className="finance-money">{money(row.monthly_interest_amount,row.currency)}<small>{row.interest_type==='percentage'?`${row.interest_rate}% monthly`:'Flat monthly amount'}</small></td><td><strong className={due?'collection-due-text':''}>{row.next_interest_date}</strong>{due&&<small>{Number(row.days_overdue)>0?`${row.days_overdue} days overdue`:'Due today'}</small>}</td><td>{money(row.total_interest_paid,row.currency)}</td><td><span className={`finance-badge ${row.status==='closed'?'approved':due?'rejected':'pending'}`}>{row.status==='closed'?'Closed':due?'Payment due':'Active'}</span></td><td><div className="finance-actions"><button className="secondary-btn" onClick={()=>history(row)}>History</button>{row.status==='active'&&<button className="primary-btn" onClick={()=>openPay(row)}>Pay interest</button>}<button className="secondary-btn" onClick={()=>toggle(row)}>{row.status==='active'?'Close':'Reopen'}</button></div></td></tr>})}{!visible.length&&<tr><td colSpan="8" className="collection-empty">No investor accounts found.</td></tr>}</tbody></table></div></section>

    {modal?.type==='add'&&<Dialog title="Add investor" subtitle="Record money received and define the monthly interest agreement" close={()=>setModal(null)}><form onSubmit={create}><div className="finance-transaction-form-grid"><Field label="Company"><select value={modal.company_id} onChange={e=>setModal({...modal,company_id:e.target.value})} required><option value="">Select company</option>{data.companies.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Investor name"><input value={modal.investor_name} onChange={e=>setModal({...modal,investor_name:e.target.value})} required/></Field><Field label="Phone"><input value={modal.phone} onChange={e=>setModal({...modal,phone:e.target.value})}/></Field><Field label="Email"><input type="email" value={modal.email} onChange={e=>setModal({...modal,email:e.target.value})}/></Field><Field label="ID / registration number"><input value={modal.id_number} onChange={e=>setModal({...modal,id_number:e.target.value})}/></Field><Field label="Investment received"><input type="number" min="0.01" step="0.01" value={modal.investment_amount} onChange={e=>setModal({...modal,investment_amount:e.target.value})} required/></Field><Field label="Interest method"><select value={modal.interest_type} onChange={e=>setModal({...modal,interest_type:e.target.value})}><option value="percentage">Percentage per month</option><option value="flat_amount">Flat amount per month</option></select></Field><Field label={modal.interest_type==='percentage'?'Monthly interest %':'Monthly interest amount'}><input type="number" min="0.01" step="0.01" value={modal.interest_rate} onChange={e=>setModal({...modal,interest_rate:e.target.value})} required/></Field><Field label="Investment received date"><input type="date" value={modal.investment_date} onChange={e=>setModal({...modal,investment_date:e.target.value})} required/></Field><Field label="First interest payout date"><input type="date" value={modal.next_interest_date} onChange={e=>setModal({...modal,next_interest_date:e.target.value})} required/></Field><Field label="Default payment method"><select value={modal.payment_method} onChange={e=>setModal({...modal,payment_method:e.target.value})}><option>Bank transfer</option><option>Cash</option><option>Cheque</option><option>UPI</option></select></Field><Field label="Investment reference"><input value={modal.reference_no} onChange={e=>setModal({...modal,reference_no:e.target.value})}/></Field></div><div className="investor-interest-preview"><span>Calculated monthly interest</span><strong>{money(modal.interest_type==='flat_amount'?modal.interest_rate:Number(modal.investment_amount||0)*Number(modal.interest_rate||0)/100,data.companies.find(c=>String(c.id)===String(modal.company_id))?.currency)}</strong></div><Footer saving={saving} close={()=>setModal(null)} text="Save investor"/></form></Dialog>}
    {modal?.type==='pay'&&<Dialog title={`Pay ${modal.row.investor_name}`} subtitle={`Interest due for ${modal.row.next_interest_date}`} close={()=>setModal(null)}><form onSubmit={pay}><div className="investor-interest-preview"><span>Expected monthly interest</span><strong>{money(modal.row.monthly_interest_amount,modal.row.currency)}</strong></div><div className="finance-transaction-form-grid"><Field label="Months being paid"><select value={modal.periods_count} onChange={e=>{const n=Number(e.target.value);setModal({...modal,periods_count:n,amount:Number(modal.row.monthly_interest_amount)*n})}}>{[1,2,3,4,5,6,12].map(n=><option value={n} key={n}>{n} month{n>1?'s':''}</option>)}</select></Field><Field label="Amount paid"><input type="number" min="0.01" step="0.01" value={modal.amount} onChange={e=>setModal({...modal,amount:e.target.value})} required/></Field><Field label="Payment date"><input type="date" value={modal.payment_date} onChange={e=>setModal({...modal,payment_date:e.target.value})} required/></Field><Field label="Payment method"><select value={modal.payment_method} onChange={e=>setModal({...modal,payment_method:e.target.value})}><option>Bank transfer</option><option>Cash</option><option>Cheque</option><option>UPI</option></select></Field><Field label="Payment reference"><input value={modal.reference_no} onChange={e=>setModal({...modal,reference_no:e.target.value})}/></Field><Field label="Notes"><input value={modal.notes} onChange={e=>setModal({...modal,notes:e.target.value})}/></Field></div><Footer saving={saving} close={()=>setModal(null)} text="Record interest payment"/></form></Dialog>}
    {modal?.type==='history'&&<Dialog title={modal.row.investor_name} subtitle={`${modal.row.company_name} · Interest payment history`} close={()=>setModal(null)} wide><div className="finance-table-scroll investor-history"><table className="finance-table"><thead><tr><th>Payment date</th><th>Interest for</th><th>Months</th><th>Method</th><th>Reference</th><th>Receipt</th><th>Paid by</th><th>Amount</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.payment_date}</td><td>{p.interest_for_date}</td><td>{p.periods_count}</td><td>{p.payment_method}</td><td>{p.reference_no||'—'}</td><td>{p.receipt_number}</td><td>{p.paid_by_name||'—'}</td><td className="finance-money">{money(p.amount,modal.row.currency)}</td></tr>)}{!payments.length&&<tr><td colSpan="8" className="collection-empty">No interest payments recorded.</td></tr>}</tbody></table></div><footer className="finance-transaction-modal-footer"><button className="secondary-btn" onClick={()=>setModal(null)}>Close</button></footer></Dialog>}
  </div>;
}
function Metric({icon:Icon,label,value,note}){return <div className="collection-admin-metric"><span><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong>{note&&<p>{note}</p>}</div></div>}
function Field({label,children}){return <label className="finance-transaction-field"><span className="finance-transaction-label">{label}</span>{children}</label>}
function Dialog({title,subtitle,close,children,wide}){return <div className="finance-modal-backdrop"><div className={`finance-transaction-modal ${wide?'collection-profile-modal':''}`}><header className="finance-transaction-modal-head"><div><p className="eyebrow">INVESTOR</p><h2>{title}</h2><p>{subtitle}</p></div><button className="finance-modal-close" onClick={close}><X size={18}/></button></header>{children}</div></div>}
function Footer({saving,close,text}){return <footer className="finance-transaction-modal-footer"><button type="button" className="secondary-btn" onClick={close}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':text}</button></footer>}
