CREATE TABLE IF NOT EXISTS program_registry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  program_name VARCHAR(180) NOT NULL,
  environment VARCHAR(40) NOT NULL DEFAULT 'production',
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  public_url VARCHAR(500) NULL,
  git_url VARCHAR(500) NULL,
  git_branch VARCHAR(120) NULL,
  server_host VARCHAR(255) NULL,
  ssh_user VARCHAR(120) NULL,
  ssh_port INT NOT NULL DEFAULT 22,
  deployment_path VARCHAR(500) NULL,
  process_manager VARCHAR(180) NULL,
  encrypted_pem LONGTEXT NULL,
  encrypted_env LONGTEXT NULL,
  notes TEXT NULL,
  created_by INT NULL,
  updated_by INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_program_environment (program_name,environment),
  KEY ix_program_status (status),
  CONSTRAINT fk_program_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_program_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
);
