import { useEffect, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, CheckCircle2, LockKeyhole, Plus, Scale, WalletCards, X } from 'lucide-react';
import { api } from '../../lib/api';
const today=()=>new Date().toISOString().slice(0,10); const money=(value,currency='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value||0));

export default function Cashbook({defaultCompanyId=null}){
  const [companies,setCompanies]=useState([]);const [companyId,setCompanyId]=useState('');const [date,setDate]=useState(today());const [data,setData]=useState({day:{status:'open'},summary:{},entries:[]});const [modal,setModal]=useState(null);const [reopen,setReopen]=useState(null);const [error,setError]=useState('');const [saving,setSaving]=useState(false);
  const company=companies.find(c=>String(c.id)===String(companyId));
  const load=async(id=companyId,day=date)=>{if(!id)return;const result=await api.get('/frontdesk/cashbook',{params:{company_id:id,date:day}});setData(result.data||{day:{},summary:{},entries:[]});};
  useEffect(()=>{api.get('/collections/companies').then(result=>{const list=result.data||[];setCompanies(list);const preferred=list.find(c=>Number(c.id)===Number(defaultCompanyId))||list[0];if(preferred){setCompanyId(String(preferred.id));load(String(preferred.id),date);}}).catch(err=>setError(err.response?.data?.message||'Unable to load cashbook.'));},[]);
  const changeCompany=value=>{setCompanyId(value);setError('');load(value,date).catch(err=>setError(err.response?.data?.message||'Unable to load cashbook.'));};const changeDate=value=>{setDate(value);setError('');load(companyId,value).catch(err=>setError(err.response?.data?.message||'Unable to load cashbook.'));};
  const saveOpening=async event=>{event.preventDefault();setSaving(true);try{await api.put('/frontdesk/cashbook/opening',{company_id:Number(companyId),date,opening_balance:modal.amount});setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to save opening balance.');}finally{setSaving(false);}};
  const saveEntry=async event=>{event.preventDefault();setSaving(true);try{await api.post('/frontdesk/cashbook/entries',{...modal,company_id:Number(companyId),entry_date:date});setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to save cash entry.');}finally{setSaving(false);}};
  const closeDay=async event=>{event.preventDefault();setSaving(true);try{await api.post('/frontdesk/cashbook/close',{company_id:Number(companyId),date,actual_closing_balance:modal.actual,closing_notes:modal.notes});setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to close cash day.');}finally{setSaving(false);}};
  const reopenDay=async event=>{event.preventDefault();setSaving(true);try{await api.post('/frontdesk/cashbook/reopen',{company_id:Number(companyId),date,admin_password:modal.admin_password});setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to reopen cash day.');}finally{setSaving(false);}};
  const confirmReopen=async event=>{event.preventDefault();setSaving(true);setError('');try{await api.post('/frontdesk/cashbook/reopen',{company_id:Number(companyId),date,admin_password:reopen.admin_password});setReopen(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to reopen cash day.');}finally{setSaving(false);}};
  const summary=data.summary||{};const closed=data.day?.status==='closed';
  return <div className="fd-cashbook">
    <div className="fd-cashbook-toolbar"><label>Company<select value={companyId} onChange={e=>changeCompany(e.target.value)}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Cash date<input type="date" value={date} onChange={e=>changeDate(e.target.value)}/></label><span className={`fd-cash-status ${closed?'closed':''}`}>{closed?<LockKeyhole size={13}/>:<CheckCircle2 size={13}/>} {closed?'Day closed':'Day open'}</span></div>
    {error&&<div className="finance-error">{error}</div>}
    {reopen&&<CashModal title="Reopen cash day" close={()=>setReopen(null)}><form onSubmit={confirmReopen}><ModalBody><Field label="Group Admin password"><input autoFocus type="password" value={reopen.admin_password} onChange={e=>setReopen({...reopen,admin_password:e.target.value})} required/></Field></ModalBody><Actions saving={saving} cancel={()=>setReopen(null)} text="Verify and reopen"/></form></CashModal>}
    <section className="fd-cash-stats"><CashStat label="Opening cash" value={money(summary.opening_balance,company?.currency)} icon={WalletCards}/><CashStat label="Cash received" value={money(Number(summary.interest_cash_received||0)+Number(summary.manual_cash_received||0),company?.currency)} note={`${money(summary.interest_cash_received,company?.currency)} from interest`} icon={ArrowDownLeft} tone="green"/><CashStat label="Cash paid" value={money(Number(summary.office_cash_paid||0)+Number(summary.manual_cash_paid||0),company?.currency)} note={`${money(summary.office_cash_paid,company?.currency)} office expenses`} icon={ArrowUpRight} tone="red"/><CashStat label="Expected closing" value={money(summary.expected_closing,company?.currency)} icon={Scale} tone="blue"/></section>
    {closed&&<section className="fd-closing-strip"><div><span>Actual cash counted</span><strong>{money(summary.actual_closing,company?.currency)}</strong></div><div><span>Cash difference</span><strong className={Number(summary.difference)!==0?'difference':''}>{money(summary.difference,company?.currency)}</strong></div><div><span>Closed at</span><strong>{data.day.closed_at||'—'}</strong></div><button className="secondary-btn" onClick={()=>setReopen({admin_password:''})}>Reopen day</button></section>}
    <div className="finance-page-toolbar"><div><strong className="fd-cash-heading">Daily cash movements</strong><span className="fd-cash-subheading">Automatic collections and expenses appear here with manual entries.</span></div>{!closed&&<div className="finance-page-actions"><button className="secondary-btn" onClick={()=>setModal({type:'opening',amount:summary.opening_balance||''})}>Set opening cash</button><button className="primary-btn" onClick={()=>setModal({type:'entry',direction:'paid',category:'Petty cash',description:'',amount:'',reference_no:'',notes:''})}><Plus size={15}/>Cash entry</button><button className="secondary-btn" onClick={()=>setModal({type:'close',actual:summary.expected_closing,notes:''})}>Close day</button></div>}</div>
    <section className="finance-list-card"><div className="finance-table-scroll"><table className="finance-table"><thead><tr><th>Time</th><th>Source</th><th>Category</th><th>Description</th><th>Entered by</th><th>Cash in</th><th>Cash out</th></tr></thead><tbody>{data.entries?.map((entry,index)=><tr key={`${entry.source}-${entry.id}-${index}`}><td>{String(entry.created_at||'').slice(11,16)||'—'}</td><td><span className="fd-cash-source">{String(entry.source).replace('_',' ')}</span></td><td>{entry.category}</td><td><strong>{entry.description}</strong>{entry.reference_no&&<small>{entry.reference_no}</small>}</td><td>{entry.created_by_name||'—'}</td><td className="fd-cash-in">{entry.direction==='received'?money(entry.amount,company?.currency):'—'}</td><td className="fd-cash-out">{entry.direction==='paid'?money(entry.amount,company?.currency):'—'}</td></tr>)}{!data.entries?.length&&<tr><td colSpan="7" className="collection-empty">No cash movements for this date.</td></tr>}</tbody></table></div></section>
    {modal&&<CashModal title={modal.type==='opening'?'Set opening cash':modal.type==='close'?'Close cash day':'Add manual cash entry'} close={()=>setModal(null)}>{modal.type==='opening'&&<form onSubmit={saveOpening}><ModalBody><Field label="Opening cash balance"><input autoFocus type="number" min="0" step="0.01" value={modal.amount} onChange={e=>setModal({...modal,amount:e.target.value})} required/></Field></ModalBody><Actions saving={saving} cancel={()=>setModal(null)} text="Save opening"/></form>}{modal.type==='entry'&&<form onSubmit={saveEntry}><ModalBody><Field label="Entry type"><select value={modal.direction} onChange={e=>setModal({...modal,direction:e.target.value})}><option value="received">Cash received</option><option value="paid">Cash paid</option></select></Field><Field label="Category"><input value={modal.category} onChange={e=>setModal({...modal,category:e.target.value})} required/></Field><Field label="Description" full><input value={modal.description} onChange={e=>setModal({...modal,description:e.target.value})} required/></Field><Field label="Amount"><input type="number" min="0.01" step="0.01" value={modal.amount} onChange={e=>setModal({...modal,amount:e.target.value})} required/></Field><Field label="Reference"><input value={modal.reference_no} onChange={e=>setModal({...modal,reference_no:e.target.value})}/></Field><Field label="Notes" full><textarea value={modal.notes} onChange={e=>setModal({...modal,notes:e.target.value})}/></Field></ModalBody><Actions saving={saving} cancel={()=>setModal(null)} text="Save cash entry"/></form>}{modal.type==='close'&&<form onSubmit={closeDay}><div className="fd-close-summary"><span>Expected closing cash</span><strong>{money(summary.expected_closing,company?.currency)}</strong></div><ModalBody><Field label="Actual cash counted"><input autoFocus type="number" min="0" step="0.01" value={modal.actual} onChange={e=>setModal({...modal,actual:e.target.value})} required/></Field><Field label="Difference"><input value={money(Number(modal.actual||0)-Number(summary.expected_closing||0),company?.currency)} disabled/></Field><Field label="Closing notes" full><textarea value={modal.notes} onChange={e=>setModal({...modal,notes:e.target.value})}/></Field></ModalBody><Actions saving={saving} cancel={()=>setModal(null)} text="Confirm and close day"/></form>}</CashModal>}
  </div>;
}
function CashStat({label,value,note,icon:Icon,tone=''}){return <div className={`fd-cash-stat ${tone}`}><span><Icon size={18}/></span><div><small>{label}</small><strong>{value}</strong>{note&&<p>{note}</p>}</div></div>;}function CashModal({title,close,children}){return <div className="finance-modal-backdrop"><div className="finance-transaction-modal fd-cash-modal"><header className="finance-transaction-modal-head"><div><p className="eyebrow">CASHBOOK</p><h2>{title}</h2><p>Company cash for the selected working date.</p></div><button className="finance-modal-close" onClick={close}><X size={18}/></button></header>{children}</div></div>;}function ModalBody({children}){return <div className="finance-transaction-form-grid">{children}</div>;}function Field({label,children,full}){return <label className={`finance-transaction-field ${full?'finance-transaction-field-full':''}`}><span className="finance-transaction-label">{label}</span>{children}</label>;}function Actions({saving,cancel,text}){return <footer className="finance-transaction-modal-footer"><button type="button" className="secondary-btn" onClick={cancel}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':text}</button></footer>;}
