import { useEffect, useMemo, useState } from 'react';
import { BadgeIndianRupee, CreditCard, Eye, HandCoins, MapPin, Phone, Search, UserRound, X } from 'lucide-react';
import { api } from '../../lib/api';

const money=(value,currency='INR')=>new Intl.NumberFormat('en-IN',{style:'currency',currency:currency||'INR',maximumFractionDigits:2}).format(Number(value||0));

export default function CustomerDirectory({navigate}){
  const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[error,setError]=useState('');
  useEffect(()=>{api.get('/collections/customers').then(r=>setRows(r.data||[])).catch(err=>setError(err.response?.data?.message||'Unable to load customers.'));},[]);
  const customers=useMemo(()=>rows.filter(row=>[row.customer_name,row.phone,row.id_card_number,row.company_name].join(' ').toLowerCase().includes(query.toLowerCase())),[rows,query]);
  return <div className="fd-customer-directory">
    {error&&<div className="finance-error">{error}</div>}
    <div className="finance-page-toolbar collection-toolbar"><div className="finance-page-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search customer, phone or ID card"/></div><button className="primary-btn" onClick={()=>navigate('loans')}>Register new loan</button></div>
    <section className="finance-list-card"><header className="fd-directory-head"><div><strong>Customer directory</strong><span>Borrowers are saved here automatically when a loan application is registered</span></div><b>{customers.length} customers</b></header><div className="finance-table-scroll"><table className="finance-table"><thead><tr><th>Customer</th><th>Company</th><th>Contact</th><th>ID card</th><th>Loan principal</th><th>Approval</th><th></th></tr></thead><tbody>{customers.map(row=><tr key={row.id}><td><strong>{row.customer_name}</strong><small>Customer #{row.id}</small></td><td>{row.company_name}</td><td>{row.phone||'—'}</td><td>{row.id_card_number}</td><td className="finance-money">{money(row.principal_amount,row.currency)}</td><td><span className={`finance-badge ${row.approval_status==='rejected'?'rejected':row.approval_status==='approved'?'approved':'pending'}`}>{row.approval_status||'approved'}</span></td><td><button className="secondary-btn" onClick={()=>setSelected(row)}>View customer</button></td></tr>)}{!customers.length&&<tr><td colSpan="7" className="collection-empty">No customers found. Registering a loan will automatically add its borrower here.</td></tr>}</tbody></table></div></section>
    {selected&&<div className="finance-modal-backdrop"><div className="finance-transaction-modal"><header className="finance-transaction-modal-head"><div><p className="eyebrow">CUSTOMER PROFILE</p><h2>{selected.customer_name}</h2><p>{selected.company_name}</p></div><button className="finance-modal-close" onClick={()=>setSelected(null)}><X size={18}/></button></header><div className="fd-directory-profile"><div><UserRound size={17}/><span>Name</span><strong>{selected.customer_name}</strong></div><div><Phone size={17}/><span>Phone</span><strong>{selected.phone||'Not provided'}</strong></div><div><CreditCard size={17}/><span>ID card</span><strong>{selected.id_card_number}</strong></div><div><MapPin size={17}/><span>Address</span><strong>{selected.address||'Not provided'}</strong></div><div><BadgeIndianRupee size={17}/><span>Current principal</span><strong>{money(selected.principal_amount,selected.currency)}</strong></div><div><HandCoins size={17}/><span>Monthly interest</span><strong>{money(selected.monthly_interest_amount,selected.currency)}</strong></div>{selected.id_card_url&&<a href={selected.id_card_url} target="_blank" rel="noreferrer"><Eye size={15}/>View ID document</a>}</div><footer className="finance-transaction-modal-footer"><button className="secondary-btn" onClick={()=>setSelected(null)}>Close</button><button className="primary-btn" onClick={()=>{setSelected(null);navigate('loans')}}>Open loans</button></footer></div></div>}
  </div>;
}
