import { useEffect, useState } from 'react';
import { Building2, CheckCircle2, Clock3, KeyRound, Save, ShieldCheck } from 'lucide-react';
import { api } from '../../lib/api';

export default function FrontdeskSettings({ onChanged }) {
  const [companies,setCompanies]=useState([]); const [current,setCurrent]=useState(null); const [selected,setSelected]=useState('');
  const [password,setPassword]=useState(''); const [showConfirm,setShowConfirm]=useState(false); const [saving,setSaving]=useState(false);
  const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  const [history,setHistory]=useState([]);const [passwordForm,setPasswordForm]=useState({current_password:'',new_password:'',confirm:''});
  useEffect(()=>{Promise.all([api.get('/collections/companies'),api.get('/frontdesk/preferences'),api.get('/frontdesk/login-history')]).then(([companyResult,preferenceResult,historyResult])=>{setCompanies(companyResult.data||[]);setCurrent(preferenceResult.data);setSelected(String(preferenceResult.data?.default_company_id||companyResult.data?.[0]?.id||''));setHistory(historyResult.data||[]);}).catch(err=>setError(err.response?.data?.message||'Unable to load settings.'));},[]);
  const requestSave=()=>{setError('');setSuccess('');if(String(current?.default_company_id)===String(selected))return setSuccess('This company is already the default.');setShowConfirm(true);};
  const save=async event=>{event.preventDefault();setSaving(true);setError('');try{const {data}=await api.put('/frontdesk/preferences/default-company',{default_company_id:Number(selected),admin_password:password});setCurrent(data);setPassword('');setShowConfirm(false);setSuccess(`${data.default_company_name} is now the default company.`);onChanged?.(data);}catch(err){setError(err.response?.data?.message||'Unable to change default company.');}finally{setSaving(false);}};
  const changePassword=async event=>{event.preventDefault();setError('');setSuccess('');if(passwordForm.new_password!==passwordForm.confirm)return setError('New passwords do not match.');try{await api.put('/frontdesk/change-password',passwordForm);setPasswordForm({current_password:'',new_password:'',confirm:''});setSuccess('Password changed successfully.');}catch(err){setError(err.response?.data?.message||'Unable to change password.');}};
  return <div className="fd-settings fd-settings-grid"><section className="fd-settings-card"><header><span><Building2 size={20}/></span><div><strong>Default company</strong><p>Choose which company is automatically selected in customer and expense forms.</p></div></header>{error&&<div className="finance-error">{error}</div>}{success&&<div className="fd-settings-success"><CheckCircle2 size={15}/>{success}</div>}<div className="fd-settings-field"><label>Default company</label><select value={selected} onChange={e=>{setSelected(e.target.value);setSuccess('');}}>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}</select><small>Staff can still select another company while entering individual transactions.</small></div><div className="fd-settings-security"><ShieldCheck size={17}/><div><strong>Protected setting</strong><span>A Group Admin password is required whenever the default company changes.</span></div></div><button className="primary-btn" onClick={requestSave} disabled={!selected}><Save size={15}/>Save default company</button></section>
    <section className="fd-settings-card"><header><span><KeyRound size={20}/></span><div><strong>Change password</strong><p>Update the password used for this front-desk login.</p></div></header><form className="fd-password-form" onSubmit={changePassword}><label>Current password<input type="password" value={passwordForm.current_password} onChange={e=>setPasswordForm({...passwordForm,current_password:e.target.value})} required/></label><label>New password<input type="password" value={passwordForm.new_password} onChange={e=>setPasswordForm({...passwordForm,new_password:e.target.value})} required/></label><label>Confirm new password<input type="password" value={passwordForm.confirm} onChange={e=>setPasswordForm({...passwordForm,confirm:e.target.value})} required/></label><button className="primary-btn">Change password</button></form></section>
    <section className="fd-settings-card fd-login-history"><header><span><Clock3 size={20}/></span><div><strong>Recent login activity</strong><p>Latest sessions for this front-desk account.</p></div></header><div>{history.map(item=><div key={item.id}><span className="fd-login-dot"/><span><strong>{formatLoginDate(item.login_at)}</strong><small>{deviceName(item.user_agent)}</small></span><small>{item.ip_address||'Unknown IP'}</small></div>)}{!history.length&&<p className="fd-settings-empty">No login activity available.</p>}</div></section>
    {showConfirm&&<div className="finance-modal-backdrop"><div className="fd-admin-confirm"><span className="fd-admin-confirm-icon"><KeyRound size={23}/></span><p className="eyebrow">ADMIN APPROVAL</p><h2>Confirm company change</h2><p>Enter an active Group Admin password to set <strong>{companies.find(c=>String(c.id)===String(selected))?.name}</strong> as the default.</p><form onSubmit={save}><label>Group Admin password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter admin password" required/></label>{error&&<div className="finance-error">{error}</div>}<footer><button type="button" className="secondary-btn" onClick={()=>{setShowConfirm(false);setPassword('');setError('');}}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Verifying…':'Verify and save'}</button></footer></form></div></div>}
  </div>;
}

function formatLoginDate(value){if(!value)return 'Unknown time';const date=new Date(String(value).replace(' ','T'));return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(date);}
function deviceName(agent=''){if(/PowerShell/i.test(agent))return 'API verification';if(/Edg\//i.test(agent))return 'Microsoft Edge on Windows';if(/Chrome\//i.test(agent))return 'Google Chrome on Windows';if(/Firefox\//i.test(agent))return 'Mozilla Firefox';if(/Safari\//i.test(agent))return 'Safari';return 'Web browser';}
