import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Eye, FileUp, Plus, ReceiptIndianRupee, Search, WalletCards, X } from 'lucide-react';
import { api } from '../../lib/api';

const today = () => new Date().toISOString().slice(0,10);
const money = (value, currency = 'INR') => new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value||0));
const categories = ['Stationery & Paper','Tea & Refreshments','Courier & Postage','Cleaning Supplies','Local Travel','Printing','Maintenance','Utilities','Rent','Salary & Allowance','Miscellaneous'];

export default function OfficeExpenses({ defaultCompanyId = null }) {
  const [rows,setRows]=useState([]); const [summary,setSummary]=useState({}); const [companies,setCompanies]=useState([]);
  const [query,setQuery]=useState(''); const [modal,setModal]=useState(false); const [receipt,setReceipt]=useState(null);
  const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [voidExpense,setVoidExpense]=useState(null);
  const [form,setForm]=useState({company_id:'',expense_date:today(),category:'Stationery & Paper',description:'',vendor:'',amount:'',payment_method:'cash',notes:''});
  const load=async()=>{const [expenses,companyResult]=await Promise.all([api.get('/frontdesk/expenses'),api.get('/collections/companies')]);setRows(expenses.data?.rows||[]);setSummary(expenses.data?.summary||{});setCompanies(companyResult.data||[]);if(!form.company_id&&companyResult.data?.[0]){const preferred=companyResult.data.find(company=>Number(company.id)===Number(defaultCompanyId))||companyResult.data[0];setForm(current=>({...current,company_id:String(preferred.id)}));}};
  useEffect(()=>{load().catch(err=>setError(err.response?.data?.message||'Unable to load office expenses.'));},[]);
  const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase())),[rows,query]);
  const submit=async event=>{event.preventDefault();setSaving(true);setError('');try{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,value));if(receipt)body.append('receipt',receipt);await api.post('/frontdesk/expenses',body);setModal(false);setReceipt(null);setForm(current=>({...current,expense_date:today(),description:'',vendor:'',amount:'',notes:''}));await load();}catch(err){setError(err.response?.data?.message||'Unable to record expense.');}finally{setSaving(false);}};
  const cancelExpense=async event=>{event.preventDefault();setSaving(true);setError('');try{await api.post(`/frontdesk/expenses/${voidExpense.id}/void`,{admin_password:voidExpense.admin_password,reason:voidExpense.reason});setVoidExpense(null);await load();}catch(err){setError(err.response?.data?.message||'Unable to cancel expense.');}finally{setSaving(false);}};
  return <div className="fd-expenses">
    <section className="fd-expense-stats"><ExpenseStat icon={ReceiptIndianRupee} label="Spent today" value={money(summary.today_total)}/><ExpenseStat icon={WalletCards} label="Cash paid today" value={money(summary.today_cash)}/><ExpenseStat icon={CalendarDays} label="This month" value={money(summary.month_total)}/><ExpenseStat icon={ReceiptIndianRupee} label="Entries today" value={summary.today_count||0}/></section>
    {error&&<div className="finance-error">{error}</div>}
    <div className="finance-page-toolbar"><div className="finance-page-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search expense, vendor or category"/></div><button className="primary-btn" onClick={()=>{setError('');setModal(true);}}><Plus size={16}/>Add expense</button></div>
    <section className="finance-list-card"><div className="finance-table-scroll"><table className="finance-table fd-expense-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Paid to</th><th>Method</th><th>Receipt</th><th>Status</th><th>Amount</th><th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id} className={row.status==='voided'?'fd-row-voided':''}><td>{row.expense_date}</td><td><span className="fd-expense-category">{row.category}</span></td><td><strong>{row.description}</strong>{row.notes&&<small>{row.notes}</small>}</td><td>{row.vendor||'—'}</td><td className="finance-type">{row.payment_method}</td><td>{row.receipt_url?<a className="fd-receipt-link" href={row.receipt_url} target="_blank" rel="noreferrer"><Eye size={13}/>View</a>:'—'}</td><td><span className={`finance-badge ${row.status==='voided'?'rejected':'approved'}`}>{row.status||'posted'}</span></td><td className="finance-money">{money(row.amount,row.currency)}</td><td>{row.status!=='voided'&&<button className="fd-cancel-link" onClick={()=>setVoidExpense({...row,admin_password:'',reason:''})}>Cancel</button>}</td></tr>)}{!filtered.length&&<tr><td colSpan="9" className="collection-empty">No office expenses recorded yet.</td></tr>}</tbody></table></div></section>
    {modal&&<div className="finance-modal-backdrop"><div className="finance-transaction-modal fd-expense-modal"><header className="finance-transaction-modal-head"><div><p className="eyebrow">OFFICE EXPENSE</p><h2>Record daily expense</h2><p>Enter paper, tea, travel or another office operating cost.</p></div><button className="finance-modal-close" onClick={()=>setModal(false)}><X size={18}/></button></header><form onSubmit={submit}><div className="finance-transaction-form-grid">
      <Field label="Company" required><select value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})} required>{companies.map(company=><option key={company.id} value={company.id}>{company.name}</option>)}</select></Field>
      <Field label="Expense date" required><input type="date" value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})} required/></Field>
      <Field label="Category" required><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(category=><option key={category}>{category}</option>)}</select></Field>
      <Field label="Amount" required><input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0.00" required/></Field>
      <Field label="Description" required full><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Example: A4 paper for office printer" required/></Field>
      <Field label="Paid to / vendor"><input value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})} placeholder="Shop or person name"/></Field>
      <Field label="Payment method"><select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></Field>
      <Field label="Bill or receipt" full><label className={`fd-file-drop ${receipt?'selected':''}`}><input type="file" accept="image/*,.pdf" onChange={e=>setReceipt(e.target.files?.[0]||null)}/><FileUp size={22}/><span><strong>{receipt?receipt.name:'Upload bill or receipt'}</strong><small>{receipt?`${(receipt.size/1024).toFixed(0)} KB · Click to replace`:'JPG, PNG or PDF · Maximum 25 MB'}</small></span></label></Field>
      <Field label="Notes" full><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Optional additional information"/></Field>
    </div><footer className="finance-transaction-modal-footer"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Cancel</button><button className="primary-btn" disabled={saving}>{saving?'Saving…':'Save expense'}</button></footer></form></div></div>}
    {voidExpense&&<div className="finance-modal-backdrop"><div className="fd-admin-confirm"><p className="eyebrow">ADMIN APPROVAL</p><h2>Cancel office expense</h2><p>This keeps the entry in history but removes it from expense and cash totals.</p><form onSubmit={cancelExpense}><label>Reason<input value={voidExpense.reason} onChange={e=>setVoidExpense({...voidExpense,reason:e.target.value})} required/></label><label>Group Admin password<input type="password" value={voidExpense.admin_password} onChange={e=>setVoidExpense({...voidExpense,admin_password:e.target.value})} required/></label>{error&&<div className="finance-error">{error}</div>}<footer><button type="button" className="secondary-btn" onClick={()=>setVoidExpense(null)}>Back</button><button className="primary-btn" disabled={saving}>{saving?'Verifying…':'Cancel expense'}</button></footer></form></div></div>}
  </div>;
}

function ExpenseStat({icon:Icon,label,value}){return <div className="finance-stat fd-expense-stat"><div className="finance-stat-icon"><Icon size={17}/></div><span>{label}</span><strong>{value}</strong></div>;}
function Field({label,children,required,full}){return <label className={`finance-transaction-field ${full?'finance-transaction-field-full':''}`}><span className="finance-transaction-label">{label}{required&&<em>*</em>}</span>{children}</label>;}
